# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Executar comandos
        run: |
          echo "Este é o primeiro passo do meu trabalho."
          # Adicione outros comandos aqui, como testes, compilação, etc.
